app/users/forms.py
from flask.ext.wtf import Form, TextField, PasswordField, BooleanField
from flask.ext.wtf import Required, Email, EqualTo

class LoginForm(Form):
	pass
	# email = TextField('Email address', [Required(), Email()])
	# password = PasswordField('Password', [Required()])

class RecoverPasswordForm(Form):
	email = TextField('Email address', [Required(), Email()])

class RegisterForm(Form):
	name = TextField('NickName', [Required()])
	email = TextField('Email address', [Required()])
	receive_email_notification = BooleanField('Receive e-mail notifications')
	password = PasswordField('Password', [Required()])
	confirm = PasswordField('Repeat Password', [
		Required(),
		EqualTo('confirm', message='Passwords must match')
	])

app/exercises/views.py
# third party imports
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for, abort
from sqlalchemy.sql import func, extract, desc, label, exists

# local application imports
from app import db
from app.exercises.forms import IDidExerciseForm, TotalOnWeekByMonthForm, ExercisesByMonthForm
from app.exercises.models import Exercise
from app.exercises.helpers import DateHelper
from app.users.constants import SESSION_NAME_USER_ID
from app.users.models import User
from app.users.requests import app_before_request
from app.users.decorators import requires_login
from app.users.notifications import send_email_to_users_have_forgotten_add_last_exercise
from app.exercises.decorators import requires_basic_auth



mod = Blueprint('exercises', __name__, url_prefix='/exercises')


@mod.before_request
def before_request():
	app_before_request()


@mod.route('/')
@mod.route('/i_did', methods=['GET'])
@requires_login
def index():
	form = IDidExerciseForm(request.form)
	return render_template('exercises/i_did.html', form=form)


@mod.route('/i_did', methods=['POST'])
@requires_login
def idid():
	form = IDidExerciseForm(request.form)

	# get the exercise date
	if(form.date_exercise_type.data == 'yesterday'):
		date_exercise = DateHelper.get_yesterday()
	else:
		date_exercise = DateHelper.string_to_date(form.date_exercise.data)

	if date_exercise > DateHelper.get_current_date().date():
		flash('Exercise date can not be newer than today')
		return render_template('exercises/i_did.html', form=form)

	if g.user.alreadyDidExercise(date_exercise):
		flash('You already did exercise on this date: %s' % date_exercise)
		return render_template('exercises/i_did.html', form=form)
	
	# create a new object to exercise
	exercise = Exercise(date_exercise, g.user.id)

	# insert the record in our db and commit it
	db.session.add(exercise)
	db.session.commit()

	# display a message to the user
	flash('Keep fitness and do it again tomorrow')

	# redirect user to the 'index' method of the user module
	return redirect(url_for('users.index'))

@mod.route('/general/')
def general():
	# get the total of exercises every user have done since the begin
	results = db.session.query(User.name, func.count(User.name).label('total'))\
						.filter(Exercise.user_id == User.id)\
						.group_by(User.name)\
						.order_by(User.name)\
						.all()

	# convert list to dictonary
	data = {name: str(total) for (name, total) in results}

	return render_template('exercises/general.html', data=data)


@mod.route('/total_on_week_by_month/', methods=['GET','POST'])
@requires_login
def total_on_week_by_month():
	form = TotalOnWeekByMonthForm(request.form)

	# set all months as options of SELECT element on the form
	form.months.choices = get_all_months_as_dictionary()

	# when is a POST action
	if form.validate_on_submit():
		date_selected = DateHelper.generated_id_by_month_year_to_date(form.months.data)

		# get the total exercises a user have done per week on a selected month
		results = db.session.query(extract('week', Exercise.date).label('week'), func.count(Exercise.date).label('total'))\
						.group_by(extract('week', Exercise.date))\
						.order_by('week')\
						.filter(extract('month', Exercise.date) == date_selected.month)\
						.filter(extract('year', Exercise.date) == date_selected.year)\
						.filter(Exercise.user_id == g.user.id)\
						.all()

		# convert list to dictonary
		data = {('Week %i of the year' % (week)): str(total) for (week, total) in results}

		return render_template('exercises/total_on_week_by_month.html', form=form, data=data)
	return render_template('exercises/total_on_week_by_month.html', form=form)


@mod.route('/exercises_by_month/', methods=['GET','POST'])
@requires_login
def exercises_by_month():
	form = ExercisesByMonthForm(request.form)

	# set all months as options of SELECT element on the form
	form.months.choices = get_all_months_as_dictionary()

	#
	# GET
	#
	if request.method == 'GET':
		return render_template('exercises/exercises_by_month.html', form=form)

	#
	# POST
	#
	if request.form["action"] == "Search":
		exercises = get_exercises_by_month(form.months.data)

	elif request.form["action"] == "Delete":
		if not request.form.getlist('do_delete'):
			exercises = get_exercises_by_month(form.months.data)
			flash('Select least one exercise to delete')
		else:
			for id_exercise in request.form.getlist('do_delete'):
				# get exercise by id
				exercise = Exercise.query.get(int(id_exercise))
				# delete
				db.session.delete(exercise)
			
			# commit
			db.session.commit()

			flash('Exercise(s) was(were) deleted successfully', 'success')
			return redirect(url_for('users.index'))

	return render_template('exercises/exercises_by_month.html', exercises=exercises, form=form)


@mod.route("/mark_exercise_by_email/<email_token>", methods=['GET'])
def mark_exercise_by_email(email_token):

	date_exercise = DateHelper.get_yesterday()

	user = User.query.filter_by(email_exercise_token=email_token).first()

	if(user is None):
		flash('Operation not allowed')
		return abort(404)

	if user.alreadyDidExercise(date_exercise):
		flash('You already did exercise on this date: %s' % date_exercise)
		return redirect(url_for('index'))

	# create a new object to exercise
	exercise = Exercise(date_exercise, user.id)

	# insert the record in our db and commit it
	db.session.add(exercise)
	db.session.commit()

	# display a message to the user
	flash('Keep fitness and do it again tomorrow')

	return redirect(url_for('index'))


@mod.route("/send_exercise_notifications/", methods=['GET'])
@requires_basic_auth
def send_exercise_notifications():

	try:
		# send notification
		send_email_to_users_have_forgotten_add_last_exercise()
	except:
		return 'Fail'

	return 'Sent'


def get_exercises_by_month(date_search):
	date_selected = DateHelper.generated_id_by_month_year_to_date(date_search)

	user_has_exercises = db.session.query(exists().where(Exercise.user_id == g.user.id)).scalar()

	if not user_has_exercises:
		flash('You don\'t have any exercises registered')
		return []

	exercises = db.session.query(Exercise)\
		.order_by(Exercise.date)\
		.filter(
			Exercise.user_id == g.user.id,\
			extract('month', Exercise.date) == date_selected.month,\
		).all()

	return exercises

def get_all_months_as_dictionary():
	# get all months a user have done exercises
	all_months = db.session.query(label('year', extract('year', Exercise.date)), label('month', extract('month', Exercise.date)))\
						.group_by('year', 'month')\
						.order_by('year desc, month desc')\
						.filter(Exercise.user_id == g.user.id)\
						.all()

	# convert list result to list dates
	all_months_as_date = [DateHelper.string_to_date(('%i/%i/1' % (year, month))) for (year, month) in all_months]

	# convert list to dictionary
	return [(DateHelper.generate_id_by_month_year(item), 
			DateHelper.date_to_year_month_string(item)) 
			for item in all_months_as_date]

app/users/views.py
# third party imports
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for, abort
from werkzeug import check_password_hash, generate_password_hash
from datetime import datetime
from sqlalchemy.sql import or_


# local application imports
from app import db, facebook
from app.users.forms import RegisterForm, LoginForm, RecoverPasswordForm
from app.users.models import User
from app.users.requests import app_before_request
from app.users.decorators import requires_login, redirect_to_profile_logged_users
from app.users.constants import SESSION_NAME_USER_ID
from app.exercises.models import Exercise
from app.users.notifications import send_email_to_recover_user_password

mod = Blueprint('users', __name__, url_prefix='/users')


@mod.before_request
def before_request():
    app_before_request()


@mod.route('/')
@mod.route('/me/')
@requires_login
def index():
    return render_template('users/profile.html', user=g.user)


# @mod.route('/login/', methods=['GET', 'POST'])
# @redirect_to_profile_logged_users
# def login():
#   form = LoginForm(request.form)

#   # make sure data are valid, but doesn't validate password is right
#   if form.validate_on_submit():
#       user = User.query.filter_by(email=form.email.data).first()
#       # we use werzeug to validate user's password
#       if user and check_password_hash(user.password, form.password.data):
#           # the session can't be modified as it's signed,
#           # it's a safe place to store the user id
#           session[SESSION_NAME_USER_ID] = user.id
#           flash('Welcome %s' % user.name)
#           return redirect(url_for('users.index'))
#       flash('Wrong email or password', 'error-message')
#   return render_template( 'users/login.html', form=form)


# @mod.route('/recover_password/', methods=['GET', 'POST'])
# @redirect_to_profile_logged_users
# def recover_password():
#     form = RecoverPasswordForm(request.form)

#     if form.validate_on_submit():
#         user = User.query.filter_by(email=form.email.data).first()
#         if user:
#             send_email_to_recover_user_password(form.email.data)
#             flash('Email sent with your password recovery')
#             return redirect(url_for('users.login'))
#         else:   
#             flash('Wrong email', 'error-message')
            
#     return render_template('users/recover_password.html', form=form)


# @mod.route("/recover_password_key/<key>", methods=['GET'])
# def recover_password_key(key):
#     # get user by key
#     user = User.query.filter_by(key_recover_password=key).first()

#     if(user is None):
#         flash('Operation not allowed')
#         return abort(404)

#     # the user verification is ok, then we can login him
#     session[SESSION_NAME_USER_ID] = user.id

#     # reset key and commit changes
#     user.key_recover_password = None
#     db.session.commit()

#     # display a message to the user
#     flash('To complete the password recovery, choose a new password and save it')

#     return redirect(url_for('users.edit'))


@mod.route('/register/', methods=['GET', 'POST'])
@redirect_to_profile_logged_users
def register():
    form = RegisterForm(request.form)

    if form.validate_on_submit():

        userRegistered = User.query.filter(or_(User.name == form.name.data,\
                                                User.email == form.email.data)).first()
        if userRegistered is not None:
            flash('Email or user already is registered')
            return render_template('users/register.html', form=form)

        # create an user instance not yet stored in the database
        user = User.CreateUser(form.name.data, form.email.data,\
                        generate_password_hash(form.password.data),\
                        form.receive_email_notification.data)

        # insert the record in our database and commit it
        db.session.add(user)
        db.session.commit()

        # log the user in, as he now has an id
        session[SESSION_NAME_USER_ID] = user.id

        # flash will display a message to the user
        flash('Thanks for registering')

        # redirect user to the 'index' method of the user module
        return redirect(url_for('users.index'))
    return render_template('users/register.html', form=form)

@mod.route('/edit/', methods=['GET', 'POST'])
@requires_login
def edit():
    form = RegisterForm(request.form)

    if request.method == 'GET':
        form.name.data = g.user.name
        form.email.data = g.user.email
        form.receive_email_notification.data = g.user.receive_email_notification

    if form.validate_on_submit():

        userRegistered = User.query.filter(or_(User.name == form.name.data,\
                                                User.email == form.email.data))\
                                    .filter(User.id != g.user.id)\
                                    .first()

        # verify if this email or user is alredy used
        if userRegistered is not None:
            flash('Email or user already is registered for another person')
            return render_template('users/edit.html', form=form)

        # get user from the database
        user = User.query.get(g.user.id)

        # update values
        user.name = form.name.data
        user.email = form.email.data
        user.password = generate_password_hash(form.password.data)
        user.receive_email_notification = form.receive_email_notification.data

        # update the record in our database and commit it
        db.session.commit()

        # flash will display a message to the user
        flash('User edited successfully')

        # redirect user to the 'index' method of the user module
        return redirect(url_for('users.index'))
    return render_template('users/edit.html', form=form)

@mod.route('/logout/', methods=['GET'])
def logout():
    # remove the username from the session if it's there
    session.pop(SESSION_NAME_USER_ID, None)

    # flash will display a message to the user
    flash('Do not forget keep the exercises')

    # redirect user to the 'index' method of the user module
    return redirect(url_for('users.login'))


@mod.route('/my_reports', methods=['GET'])
@requires_login
def my_reports():
    return render_template('users/my_reports.html')


# FACEBOOK

@mod.route('/login/')
@redirect_to_profile_logged_users
def login():
  return render_template('users/login.html')


@mod.route('/login/facebook')
def login_facebook():
    return facebook.authorize(callback=url_for('users.facebook_authorized',
        next=request.args.get('next') or request.referrer or None,
        _external=True))


@mod.route('/login/authorized')
@facebook.authorized_handler
def facebook_authorized(resp):
    if resp is None:
        return 'Access denied: reason=%s error=%s' % (
            request.args['error_reason'],
            request.args['error_description']
        )
    session['oauth_token'] = (resp['access_token'], '')
    me = facebook.get('/me')

    user = User.create_or_update_user_from_oauth(\
            name=me.data['name'], 
            username=me.data['username'], 
            email=me.data['email'], 
            oauth_key=me.data['id'])

    session[SESSION_NAME_USER_ID] = user.id
    flash('Welcome %s' % user.name)
    return redirect(url_for('users.index'))


@facebook.tokengetter
def get_facebook_oauth_token():
    return session.get('oauth_token')

app/templates/users/edit.html
{% extends "base.html" %}

{% block content %}
  {% from "forms/macros.html" import render_field %}
  <form method="POST" action="." class="form">
    {{ form.csrf_token }}
    {{ render_field(form.name, class="input text") }}
    {{ render_field(form.email, class="input text") }}
    {{ render_field(form.password, class="input text") }}
    {{ render_field(form.confirm, class="input text") }}
    {{ render_field(form.receive_email_notification) }}
    <em>Mark this field to receive a notification when forget to register a exercise</em>
    <input type="submit" value="Edit">
  </form>
{% endblock %}

{% block footer %}
  <a class="bt-action bt-action-user" href="{{ url_for('users.index') }}">
    <span>Profile</span>
  </a>
{% endblock %}

app/templates/users/login.html
{% extends "base.html" %}

{% block content %}
	
    <p>
      Sign with facebook account to control your exercises.
    </p>
      <a href="{{ url_for('users.login_facebook') }}" id="btn-login"></a>
{% endblock %}

{% block footer %}
	<a class="bt-action bt-action-home" href="{{ url_for('index') }}">
		<span>Home</span>
	</a>
	<a class="bt-action bt-action-user" href="{{ url_for('users.register') }}">
		<span>Register</span>
	</a>
{% endblock %}

app/templates/users/my_reports.html
{% extends "base.html" %}

{% block content %}
	<h2>My Reports</h2>
	<b>Charts</b>
	<ul id="profile-results">
		<li><a href="{{ url_for('exercises.total_on_week_by_month') }}">Total exercises on weeks by month</a></li>
		<li><a href="{{ url_for('exercises.general') }}">Total exercises all users have done since the begin</a></li>
	</a>
	</ul>
{% endblock %}

{% block footer %}
	<a class="bt-action bt-action-user" href="{{ url_for('users.index') }}">
		<span>Profile</span>
	</a>
{% endblock %}

app/templates/users/profile.html
{% extends "base.html" %}

{% block content %}
	<img src="{{ user.get_picture() }}" />
	<h2>{{ user.getNameTitle() }}</h2>

	<b>How you are going</b>
	<ul id="profile-results">
		<li><b>{{ "%02d" % user.getTotalExercisesCurrentWeek() }}</b> this week</li>
		<li><b>{{ "%02d" % user.getTotalExercisesCurrentMonth() }}</b> this month</li>
		<li><b>{{ "%02d" % user.getTotalExercises() }}</b> since the begin</li>
	</ul>
	<br>
	<a class="bt-action bt-action-green bt-action-run" href="{{ url_for('exercises.idid') }}" style="width:95%">
		<span style="text-align: center;line-height: 25px;font-size: 15px;">I Sweated Yesterday</span>
	</a>
	<div class="clear"></div>
{% endblock %}

{% block footer %}

	<div>
		<a class="bt-action bt-action-list" href="{{ url_for('exercises.exercises_by_month') }}" style="float:left; width: 33%;">
			<span>Exercises</span>
		</a>
		<a class="bt-action bt-action-chart" href="{{ url_for('users.my_reports') }}" style="float:left; width: 25%;">
			<span>Charts</span>
		</a>
		<a class="bt-action bt-action-edit" href="{{ url_for('users.edit') }}" style="float:left; width: 23%;margin-right: 0px;">
			<span>Edit</span>
		</a>
	</div>

{% endblock %}

app/templates/users/recover_password.html
{% extends "base.html" %}

{% block content %}
	{% from "forms/macros.html" import render_field %}
	<form method="POST" action="." class="form">
		{{ form.csrf_token }}
		{{ render_field(form.email, class="input text") }}
		<input type="submit" value="Recover">
	</form>
{% endblock %}

{% block footer %}
	<a class="bt-action bt-action-home" href="{{ url_for('index') }}">
		<span>Home</span>
	</a>
	<a class="bt-action bt-action-user" href="{{ url_for('users.login') }}">
		<span>Login</span>
	</a>
{% endblock %}

app/templates/users/register.html
{% extends "base.html" %}

{% block content %}
  {% from "forms/macros.html" import render_field %}
  <form method="POST" action="." class="form">
    {{ form.csrf_token }}
    {{ render_field(form.name, class="input text") }}
    {{ render_field(form.email, class="input text") }}
    {{ render_field(form.password, class="input text") }}
    {{ render_field(form.confirm, class="input text") }}
    <input type="submit" value="Register">
  </form>
{% endblock %}

{% block footer %}
  <a class="bt-action bt-action-user" href="{{ url_for('users.login') }}">
    <span>Login</span>
  </a>
{% endblock %}